### ISSUE TITLE
Improve syntax highlighting of quick info when Codist "syntax highlight" is disabled

### ISSUE THREAD

**Issue by laicasaane** [wmjordan/Codist#113] opened 2019-11-26 05:40 UTC
I'm only using "syntax highlight" of VS 2019.

![image](https://user-images.githubusercontent.com/1594982/69602286-a24f8980-1049-11ea-9200-80a21849a8e9.png)

![image](https://user-images.githubusercontent.com/1594982/69602364-d4f98200-1049-11ea-81f0-c0ff5ef1b1e0.png)

And this is a snippet of the class with correct colors:
![image](https://user-images.githubusercontent.com/1594982/69602455-37528280-104a-11ea-9e9a-b97d0c120a08.png)

**Comment by wmjordan** [comment] 2019-11-26 06:12
Thank you for reporting this problem.
I reproduced it just now.
I will look into it and see what I can do to adapt those newly introduced C# syntax styles in VS 2019 to those in Codist.

**Comment by wmjordan** [comment] 2019-11-26 07:32
There is a fix for this issue. Please try the new beta in #108.

**Comment by laicasaane** [comment] 2019-11-26 11:46
It work better than before, thanks. However, are these behaviours intended?

- Bold properties
![image](https://user-images.githubusercontent.com/1594982/69626738-d479df00-107b-11ea-88b9-32c4125d7493.png)

- Inconsistent parameters highlighting: some first and second params are dimmer than the rest
![image](https://user-images.githubusercontent.com/1594982/69626877-1efb5b80-107c-11ea-9d39-051dc6674f3f.png)

- Method name and first parameter are in bold
- "this" is colored incorrectly.
![image](https://user-images.githubusercontent.com/1594982/69627219-d42e1380-107c-11ea-8ca9-dee52df53e1c.png)

**Comment by wmjordan** [comment] 2019-11-27 00:53
- Bold properties: It is subtle. I will look into it.
- Inconsistent parameters highlighting: It is by design. The parameter having the same type and name as the current method in the overloads will be dimmed. So it helps us to quickly find out what parameters in the overloads are different from the current one.
- Method name and first parameter are bold: Since you are hovering on the first argument of your `Transition` method, it emphasize the method name and **THE** argument, so to help you figure out the result of `Start.To(Users)` will be used as the first argument to the `Transition` method. If you hover on the `Start` at the same line of the method, the `startState` will be set to bold.
- "this" is colored incorrectly: I will check this.

**Comment by wmjordan** [comment] 2019-11-27 04:08
Please test the new beta.

**Comment by laicasaane** [comment] 2019-11-28 08:59
It works well now, thank you.

**Comment by wmjordan** [comment] 2019-11-30 01:42
I am closing this issue.
Feel free to open a new one if you encounter another problem.

**Closed by wmjordan** 2019-11-30 01:42 UTC
Labels: QuickInfo
