### ISSUE TITLE
Rearranging Source Code Members with Menus in Navi Bar

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#49] opened 2018-10-27 00:56 UTC
Drag and drop/Rearrange items in Navi Bar:

- [x] Within the same type
- [x] To another code file within the partial type
- [x] To another type within the same code file
- [x] Copy/Delete/Duplicate the member
- [x] Reformat the member

**Comment by wmjordan** [comment] 2018-10-28 02:51
@fitdev, I downloaded and installed the latest version of _CodeNav_ but I could not see there was drag-and-drop support in it. _SuperCharger_ has that feature but it is close-sourced.
Can someone provide an example of WPF drag-and-drop on `MenuItem`s?

**Comment by fitdev** [comment] 2018-10-28 09:30
I am sorry to have caused confusion. I must have confused it with some other extension - possibly _SuperCharger_. I will let you know if I come across any open source extension that has drag-drop support.

**Comment by wmjordan** [comment] 2018-11-15 07:41
I tried to write some code to support the drag and drop.
While the drag operation on the menu items began, the menu automatically closed.
I tried to reopen the menu and drop the items onto the reopened menu items.
`FatalExecutionException`s would throw after that.
[A similar problem](https://stackoverflow.com/q/7088432) was posted on StackOverflow

**Comment by wmjordan** [comment] 2018-11-16 08:06
Yes, that was what I was considering to do.
The "pinning" means making another window, in which types and members will be listed and we can drag and drop to reorder items.

**Comment by wmjordan** [comment] 2018-11-16 08:08
However, that makes almost no difference against _CodeNav_. I don't very want to reinvent the wheel.

**Comment by wmjordan** [comment] 2018-11-19 03:02
Understood.
I personally and occasionally need to rearrange members as well.
I'll try to see how to implement this.

**Comment by fitdev** [comment] 2019-02-05 06:34
Just a quick thought: When you implement drag-drop support in the NaviBar, it would be even better if it could be applied to partial types as well. That way one could move members between files without having to open them in the editor!

**Comment by wmjordan** [comment] 2019-02-07 03:15
Good thought.
Very unfortunately I got very sick recently and I would not continue with this project until I got 120% recovered.

**Comment by fitdev** [comment] 2019-02-07 06:51
Sorry to hear about that. I hope you get better soon!

**Comment by wmjordan** [comment] 2019-02-12 01:41
Thanks for your bless.
I am a bit better now. But my vacation was ended.

**Comment by fitdev** [comment] 2019-02-13 07:46
Too bad you could not enjoy your vacation as much because of the illness, but hopefully you did get some rest. I wish you a complete recovery soon!

**Comment by wmjordan** [comment] 2019-05-15 06:24
Here is a new version for the next big changes!
The drag and drop function in NaviBar has been released.

[Codist.zip](https://github.com/wmjordan/Codist/files/3181126/Codist.zip)

**Comment by wmjordan** [comment] 2019-05-15 06:40
This version has disabled tool tips for symbol items. Please test whether the hover delay in #48  is still noticeable.

**Comment by fitdev** [comment] 2019-05-15 07:41
That was much faster than I thought! Great work!

The drag-drop support works great! I have tested it on only a few cases for now, but so far I did not encounter any issues. I will let you know if I encounter some bugs.

One small thing about drag-drop - it would be really nice if an insertion point line can be drawn between the items where the item being dragged would land. BTW the tooltips that appear saying where item will be inserted are very nice and helpful!

For the future version, perhaps you might further extend drag-drop feature by allowing multiple selection and drag-drop of multiple items. Perhaps a multi-item selection mode can be activated by either a keyboard shortcut, or Ctrl-clicking, or a dedicated button at the top of the dropdown.

No, there is no hover delay anymore. In the previous version it was only happening while the dropdown was open _and tooltip has been displayed at least once_. If the tooltip was never displayed while the dropdown was open, there was no delay. After dropdown was closed and reopened, there was no delay either, until tooltip was shown. In other words, after dropdown is closed, the behavior is reset (back to normal) until the tooltip is displayed again.

**Comment by wmjordan** [comment] 2019-05-15 10:52
> if an insertion point line can be drawn between the items where the item being dragged would land

Yes, it is the conventional way. But I don't know whether it is possible for me to implement that in the recent future.


> it would be even better if it could be applied to partial types as well

The implementation does support dragging among partial types. Please test it and see how it goes. There could be some bugs since I have not yet fully tested in such kinds of cases.

> perhaps you might further extend drag-drop feature by allowing multiple selection and drag-drop of multiple items

I hope so too.

> In the previous version it was only happening while the dropdown was open _and tooltip has been displayed at least once_.

It is really weird. I never experienced this on my machine. I am going to rewrite the tool tip anyway.
Could you give some suggestions on when and where the tips should be displayed?

**Comment by fitdev** [comment] 2019-05-15 11:29
> Yes, it is the conventional way. But I don't know whether it is possible for me to implement that in the recent future.

Perhaps you can implement it via a style change for the item _over_ which the other item is being dragged. Such that either the top or the bottom borders are drawn with a thick brush, "simulating" the insertion point.

> The implementation does support dragging among partial types. Please test it and see how it goes. There could be some bugs since I have not yet fully tested in such kinds of cases.

That's great! I will try to test it ASAP and let you know if I encounter any issues.

> It is really weird. I never experienced this on my machine. I am going to rewrite the tool tip anyway.
Could you give some suggestions on when and where the tips should be displayed?

I think the way it currently works is acceptable (apart from the hover delay issue of course). The tooltip itself should be displayed after a short delay most likely. Maybe you can add an option that controls whether tooltips are shown instantly or after a delay - but that's really up to you. I will be fine with or without such an option.

As for where tooltips should be displayed, what do you mean exactly? I don;t have a strong preference, but perhaps you can display them in a similar fashion to how Intellisense tooltips are displayed - outside of the dropdown? But these are really minor details, and I am not sure if it is worth spending your development efforts in this area.

**Comment by fitdev** [comment] 2019-05-15 13:36
Although unrelated to this issue, I am posting this bug report here, since it applies to the very latest version of Codist you provided here. I was just scrolling through a .cs file, when VS informed me of an extension error (VS did not crash) and Codist continued to work afterwards, so it's not a major issue, still I thought I would report it:

From the VS activity log:

```

System.AggregateException: One or more errors occurred. 
---> System.NullReferenceException: Object reference not set to an instance of an object. at
Codist.SymbolFormatter.ToUIText(InlineCollection text, ISymbol symbol, String alias) in E:\Codes\Open Source Projects\Codist\Codist\Helpers\SymbolFormatter.cs:line 143 at
Codist.SymbolFormatter.ToUIText(InlineCollection block, TypedConstant constant) in E:\Codes\Open Source Projects\Codist\Codist\Helpers\SymbolFormatter.cs:line 316 at
Codist.SymbolFormatter.ToUIText(InlineCollection block, AttributeData item) in E:\Codes\Open Source Projects\Codist\Codist\Helpers\SymbolFormatter.cs:line 357 at
Codist.QuickInfo.CSharpQuickInfo.ShowAttributes(IList`1 qiContent, ImmutableArray`1 attrs) in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfo.cs:line 907 at
Codist.QuickInfo.CSharpQuickInfo.ShowAttributesInfo(IList`1 qiContent, ISymbol symbol) in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfo.cs:line 549 at
Codist.QuickInfo.CSharpQuickInfo.AugmentQuickInfoSession(IQuickInfoSession session, IList`1 qiContent, ITrackingSpan& applicableToSpan) in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfo.cs:line 183 at
Microsoft.VisualStudio.Language.Intellisense.Implementation.LegacyQuickInfoSource.AugmentQuickInfoSession(IAsyncQuickInfoSession session, IList`1 content, ITrackingSpan& applicableToSpan) at
Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<TryComputeContentFromLegacySourceAsync>d__46.MoveNext() --- End of stack trace from previous location where exception was thrown --- at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at
Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<ComputeSourceContentAsync>d__39.MoveNext() --- End of inner exception stack trace --- at
Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<UpdateAsync>d__32.MoveNext() --- End of stack trace from previous location where exception was thrown --- at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at
Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoPresentationSession.<UpdateAsync>d__5.MoveNext() ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object. at
Codist.SymbolFormatter.ToUIText(InlineCollection text, ISymbol symbol, String alias) in E:\Codes\Open Source Projects\Codist\Codist\Helpers\SymbolFormatter.cs:line 143 at
Codist.SymbolFormatter.ToUIText(InlineCollection block, TypedConstant constant) in E:\Codes\Open Source Projects\Codist\Codist\Helpers\SymbolFormatter.cs:line 316 at
Codist.SymbolFormatter.ToUIText(InlineCollection block, AttributeData item) in E:\Codes\Open Source Projects\Codist\Codist\Helpers\SymbolFormatter.cs:line 357 at
Codist.QuickInfo.CSharpQuickInfo.ShowAttributes(IList`1 qiContent, ImmutableArray`1 attrs) in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfo.cs:line 907 at
Codist.QuickInfo.CSharpQuickInfo.ShowAttributesInfo(IList`1 qiContent, ISymbol symbol) in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfo.cs:line 549 at
Codist.QuickInfo.CSharpQuickInfo.AugmentQuickInfoSession(IQuickInfoSession session, IList`1 qiContent, ITrackingSpan& applicableToSpan) in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfo.cs:line 183 at
Microsoft.VisualStudio.Language.Intellisense.Implementation.LegacyQuickInfoSource.AugmentQuickInfoSession(IAsyncQuickInfoSession session, IList`1 content, ITrackingSpan& applicableToSpan) at
Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<TryComputeContentFromLegacySourceAsync>d__46.MoveNext() --- End of stack trace from previous location where exception was thrown --- at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at
Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<ComputeSourceContentAsync>d__39.MoveNext()<---
```

**Comment by wmjordan** [comment] 2019-05-16 00:57
Thank you for the bug report.
There's a new version which fixed this issue.
It also places the tool tip to the bottom of the menu.

[Codist.zip](https://github.com/wmjordan/Codist/files/3184979/Codist.zip)

**Comment by fitdev** [comment] 2019-05-16 06:47
Thank you for a quick fix, I will let you know if I encounter any other issues.

I like the new design with tolltips at the bottom! Great idea! That also fixes the tooltip delay issue as well.

Also, good idea on including the number of partial type files in the code statistics. That's very helpful too!

Great work as always!

**Comment by fitdev** [comment] 2019-05-16 06:58
Actually, just after 10 minutes of using the latest version, got another non-critical exception similar to the one I reported. It happened as I was just moving the mouse cursor over code (can't remember over which code element it was actually triggered):

```
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object. at
Codist.SymbolFormatter.ToUIText(InlineCollection text, ISymbol symbol, String alias) in E:\Codes\Open Source Projects\Codist\Codist\Helpers\SymbolFormatter.cs:line 143 at
Codist.SymbolFormatter.ToUIText(InlineCollection block, TypedConstant constant) in E:\Codes\Open Source Projects\Codist\Codist\Helpers\SymbolFormatter.cs:line 316 at
Codist.SymbolFormatter.ToUIText(InlineCollection block, AttributeData item) in E:\Codes\Open Source Projects\Codist\Codist\Helpers\SymbolFormatter.cs:line 357 at
Codist.QuickInfo.CSharpQuickInfo.ShowAttributes(IList`1 qiContent, ImmutableArray`1 attrs) in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfo.cs:line 907 at
Codist.QuickInfo.CSharpQuickInfo.ShowAttributesInfo(IList`1 qiContent, ISymbol symbol) in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfo.cs:line 549 at
Codist.QuickInfo.CSharpQuickInfo.AugmentQuickInfoSession(IQuickInfoSession session, IList`1 qiContent, ITrackingSpan& applicableToSpan) in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfo.cs:line 183 at
Microsoft.VisualStudio.Language.Intellisense.Implementation.LegacyQuickInfoSource.AugmentQuickInfoSession(IAsyncQuickInfoSession session, IList`1 content, ITrackingSpan& applicableToSpan) at
Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<TryComputeContentFromLegacySourceAsync>d__46.MoveNext() --- End of stack trace from previous location where exception was thrown --- at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at
Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<ComputeSourceContentAsync>d__39.MoveNext() --- End of inner exception stack trace --- at
Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<UpdateAsync>d__32.MoveNext() --- End of stack trace from previous location where exception was thrown --- at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at
Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoPresentationSession.<UpdateAsync>d__5.MoveNext() ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object. at
Codist.SymbolFormatter.ToUIText(InlineCollection text, ISymbol symbol, String alias) in E:\Codes\Open Source Projects\Codist\Codist\Helpers\SymbolFormatter.cs:line 143 at
Codist.SymbolFormatter.ToUIText(InlineCollection block, TypedConstant constant) in E:\Codes\Open Source Projects\Codist\Codist\Helpers\SymbolFormatter.cs:line 316 at
Codist.SymbolFormatter.ToUIText(InlineCollection block, AttributeData item) in E:\Codes\Open Source Projects\Codist\Codist\Helpers\SymbolFormatter.cs:line 357 at
Codist.QuickInfo.CSharpQuickInfo.ShowAttributes(IList`1 qiContent, ImmutableArray`1 attrs) in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfo.cs:line 907 at
Codist.QuickInfo.CSharpQuickInfo.ShowAttributesInfo(IList`1 qiContent, ISymbol symbol) in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfo.cs:line 549 at
Codist.QuickInfo.CSharpQuickInfo.AugmentQuickInfoSession(IQuickInfoSession session, IList`1 qiContent, ITrackingSpan& applicableToSpan) in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfo.cs:line 183 at
Microsoft.VisualStudio.Language.Intellisense.Implementation.LegacyQuickInfoSource.AugmentQuickInfoSession(IAsyncQuickInfoSession session, IList`1 content, ITrackingSpan& applicableToSpan) at
Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<TryComputeContentFromLegacySourceAsync>d__46.MoveNext() --- End of stack trace from previous location where exception was thrown --- at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at
Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<ComputeSourceContentAsync>d__39.MoveNext()<--- 
```
and

```
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object. at
Codist.SymbolFormatter.ToUIText(InlineCollection text, ISymbol symbol, String alias) in E:\Codes\Open Source Projects\Codist\Codist\Helpers\SymbolFormatter.cs:line 143 at
Codist.SymbolFormatter.ToUIText(InlineCollection block, TypedConstant constant) in E:\Codes\Open Source Projects\Codist\Codist\Helpers\SymbolFormatter.cs:line 316 at
Codist.SymbolFormatter.ToUIText(InlineCollection block, AttributeData item) in E:\Codes\Open Source Projects\Codist\Codist\Helpers\SymbolFormatter.cs:line 357 at
Codist.QuickInfo.CSharpQuickInfo.ShowAttributes(IList`1 qiContent, ImmutableArray`1 attrs) in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfo.cs:line 907 at
Codist.QuickInfo.CSharpQuickInfo.ShowAttributesInfo(IList`1 qiContent, ISymbol symbol) in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfo.cs:line 549 at
Codist.QuickInfo.CSharpQuickInfo.AugmentQuickInfoSession(IQuickInfoSession session, IList`1 qiContent, ITrackingSpan& applicableToSpan) in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfo.cs:line 183 at
Microsoft.VisualStudio.Language.Intellisense.Implementation.LegacyQuickInfoSource.AugmentQuickInfoSession(IAsyncQuickInfoSession session, IList`1 content, ITrackingSpan& applicableToSpan) at
Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<TryComputeContentFromLegacySourceAsync>d__46.MoveNext() --- End of stack trace from previous location where exception was thrown --- at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at
Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<ComputeSourceContentAsync>d__39.MoveNext() --- End of inner exception stack trace --- at
Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<UpdateAsync>d__32.MoveNext() --- End of stack trace from previous location where exception was thrown --- at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at
Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoPresentationSession.<UpdateAsync>d__5.MoveNext() ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object. at
Codist.SymbolFormatter.ToUIText(InlineCollection text, ISymbol symbol, String alias) in E:\Codes\Open Source Projects\Codist\Codist\Helpers\SymbolFormatter.cs:line 143 at
Codist.SymbolFormatter.ToUIText(InlineCollection block, TypedConstant constant) in E:\Codes\Open Source Projects\Codist\Codist\Helpers\SymbolFormatter.cs:line 316 at
Codist.SymbolFormatter.ToUIText(InlineCollection block, AttributeData item) in E:\Codes\Open Source Projects\Codist\Codist\Helpers\SymbolFormatter.cs:line 357 at
Codist.QuickInfo.CSharpQuickInfo.ShowAttributes(IList`1 qiContent, ImmutableArray`1 attrs) in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfo.cs:line 907 at
Codist.QuickInfo.CSharpQuickInfo.ShowAttributesInfo(IList`1 qiContent, ISymbol symbol) in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfo.cs:line 549 at
Codist.QuickInfo.CSharpQuickInfo.AugmentQuickInfoSession(IQuickInfoSession session, IList`1 qiContent, ITrackingSpan& applicableToSpan) in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfo.cs:line 183 at
Microsoft.VisualStudio.Language.Intellisense.Implementation.LegacyQuickInfoSource.AugmentQuickInfoSession(IAsyncQuickInfoSession session, IList`1 content, ITrackingSpan& applicableToSpan) at
Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<TryComputeContentFromLegacySourceAsync>d__46.MoveNext() --- End of stack trace from previous location where exception was thrown --- at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at
Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<ComputeSourceContentAsync>d__39.MoveNext()<--- 
```

**Comment by wmjordan** [comment] 2019-05-16 07:21
It is related to something that has attributes and those attributes have some constants.
Could you try to hover your mouse around your code and copy the code on which the quick info can not be displayed?

**Comment by fitdev** [comment] 2019-05-16 07:32
Just tried it on the attributes with constants (I do have those), and it works just fine - quick info is displayed for all the elements of attribute code. I will let you know then when I encounter a piece of code for which quick info is not shown. I am suing C# 8.0 Preview 5 though.

**Comment by wmjordan** [comment] 2019-05-16 07:36
According to the stack trace, the problematic "constant" means types, not numbers or strings.
Have you employed some special syntax in C# 8 on your attributes?

**Comment by fitdev** [comment] 2019-05-16 08:00
No, not on the attributes - those use regular syntax. Found it though. It triggers when I hover over a property name _within object initializer_:

![2019-05-16 10_57_50-workspace net - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/8166847/57836592-b593b980-77c9-11e9-8830-0ef71ac8c19c.jpg)

So, here if I hover over `Body`, `Height`, or `Weight` I get the error. Hope it helps.

**Comment by wmjordan** [comment] 2019-05-16 08:17
Could you post the attributes on the container types?

**Comment by wmjordan** [comment] 2019-05-16 10:21
Try this new beta version, which provides a context menu for symbol lists.
And it may fix your problem aforementioned.

[Codist.zip](https://github.com/wmjordan/Codist/files/3186588/Codist.zip)


> Maybe you can add an option that controls whether tooltips are shown instantly or after a delay

I'd love to have this. However, it is not so easy at this moment for the rewritten tool tip.

**Comment by fitdev** [comment] 2019-05-16 13:20
I like the new context menu! Very useful!

The bug still happens unfortunately. Here are some details:

This is the definition of a `Weight` member from the sample code above. (The error occurs when I hover over the `Weight` in the sample code above).
```cs
    [Ddl(Db.Weight)]
    public short? Weight { get; set; }
```

And here's the actual attribute:
```cs
  [AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
  public sealed class DdlAttribute : Attribute {

    public DdlAttribute(string name, DdlFlags flags = DdlFlags.None
      , Type converterType = null
      ) {
      Name = name;
      Flags = flags;
      ConverterType = converterType;
    }

    public string Name { get; set; }
    public DdlFlags Flags { get; set; }

    public Type ConverterType { get; set; }
    public bool HasConverter => !(ConverterType is null);
    public ITypeConverter Converter => ConverterType is null ? null : GetTypeConverter(ConverterType);
    public bool IsRequired => Flags.HasFlagSet(DdlFlags.Required);
    public bool CanBeNull => !IsRequired;
    public bool IsChildTable => Flags.HasFlagSet(DdlFlags.ChildTable);
    public bool IsUpdatable => !Flags.HasFlagSet(DdlFlags.InitialOnly);
    public bool UpdateOnUpdateOnly => Flags.HasFlagSet(DdlFlags.UpdateOnUpdateOnly);
    public bool LogUpdates => IsUpdatable && !Flags.HasFlagSet(DdlFlags.UpdateNoLog);
  }
```

Hope it helps.

**Comment by fitdev** [comment] 2019-05-16 13:27
Oh and now with the latest version, VS crashed as well after I hovered over one of the members in the Navi Bar dropdown:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Codist.SymbolFormatter.ToUIText(System.Windows.Documents.InlineCollection, Microsoft.CodeAnalysis.ISymbol, System.String)
   at Codist.SymbolFormatter.ToUIText(System.Windows.Documents.InlineCollection, Microsoft.CodeAnalysis.TypedConstant)
   at Codist.SymbolFormatter.ToUIText(System.Windows.Documents.InlineCollection, Microsoft.CodeAnalysis.AttributeData, Boolean)
   at Codist.ToolTipFactory.CreateToolTip(Microsoft.CodeAnalysis.ISymbol, Boolean, Microsoft.CodeAnalysis.Compilation)
   at Codist.Controls.SymbolList.CreateItemToolTip(System.Windows.Controls.ListBoxItem)
   at Codist.Controls.SymbolList.ShowToolTipForItem(System.Windows.Controls.ListBoxItem)
   at Codist.Controls.SymbolList.MouseMove_ChangeToolTip(System.Object, System.Windows.Input.MouseEventArgs)
   at System.Windows.Input.MouseEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by wmjordan** [comment] 2019-05-16 23:01
Thank you very much for your code. It really helps.

The reason for the crash was that there was a `null` reference passed as an argument to the attribute constructor. I did not expected that during my development.
It was also the cause for your recently reported crash.

This new version should fix the problem.
[Codist.zip](https://github.com/wmjordan/Codist/files/3189294/Codist.zip)

**Comment by fitdev** [comment] 2019-05-17 07:33
Glad it helped! I can confirm that the new version fixes the problem - it now correctly displays quick info tooltip. Thank you for fixing it so quickly! I will let you know if I encounter other issues.

**Comment by wmjordan** [comment] 2019-05-18 06:00
OK. I am closing this issue now, since all planned features are implemented. Please open a new issue if you find any problem.

**Closed** 2019-05-20 00:25 UTC
Labels: Navigation, feature request
