### ISSUE TITLE
Sub Menu Analyse references not adapted to the dark theme

### ISSUE THREAD

**Issue by Yoahn60** [wmjordan/Codist#43] opened 2018-10-03 08:22 UTC
Duplication: sorry, I just see that there was another post about it.
To delete if you can

Hello,

Sorry, I am French and my English is largely perfectible.
Thanks for your extension that combines the benefits of many others and with good performances.

it's 5 minutes I tested your extension and I just realized that the dark theme is not supported in the menu of the analyzer references.

![analyse references](https://user-images.githubusercontent.com/43807720/46398376-46af9780-c6f5-11e8-8ecb-0e4a32038d95.png)

I thank you in advance for his support.
Good work :)

**Comment by wmjordan** [comment] 2018-10-03 12:05
Thanks for posting. It is not completely a duplicate.
The dark theme issue has been partially fixed in the recent version of Codist. It was not completely themed by the dark theme, but should not look like that. On my computer, it should be like the following.

![_2018-09-25t06-40-33 786z](https://user-images.githubusercontent.com/12182730/46409133-fbbe7000-c746-11e8-8d7a-3e589d821855.png)

**Comment by wmjordan** [comment] 2018-10-03 12:14
Possible duplicate of #38.

**Comment by wmjordan** [comment] 2018-10-04 11:55
[Codist.zip](https://github.com/wmjordan/Codist/files/2446193/Codist.zip)

Please test with this beta version. It should solve your problem.

**Comment by Yoahn60** [comment] 2018-10-04 13:41
Good work !

The dark theme works in the sub menus.

Thank you for your responsiveness and good luck on this achievement.

**Comment by wmjordan** [comment] 2018-10-05 00:06
Great to hear that!

**Closed as completed** 2018-10-05 02:21 UTC
Labels: bug
