### ISSUE TITLE
Serious Performance Issues with Syntax Highlights Enabled

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#165] opened 2021-05-31 19:57 UTC
For reference, I am using latest Codist 5.11.0.6426 on VS 2019 16.11 Preview 1. However this is _not_ specific to this version of Codist or VS - I have had similar issues for a long time. It's just that now it has gotten particularly bad (it seems to "not like" certain code for whatever reason), so I decided to investigate a bit.

What I found is that generally there is a very noticeable lag when typing _when Syntax Highlight module is enabled_ (I tested various combinations of which modules in Codist are enabled and the offender seems to be Syntax Highlight. Basically when it is _on_, there is like half-a-second to a full second lag between typing characters and them appearing (of course it varies depending on the document, its size, etc., but on average it's that).

Comment Tagger seems _not_ to be the issue (since there is no difference between whether it is enabled or not).

I don't know the details of how Syntax Highlight is implemented in Codist, but my suggestion would be to postpone all work in this module until typing has stopped (i.e. > 1 second has passed). I am sure VS must inform somehow whether a user is actively typing or not. Because triggering a syntax highlight on every keystroke is very performance intensive. Alternatively maybe all this work can be shifted off the UI thread?

This is really critical, and for the moment I am forced to disable Syntax Highlight as it is preventing me from getting work done.

Note: it works ok in very small solutions, but any sizable solution with 10+ projects and a few hundred files will already lead to serious slowdowns. So, perhaps you can find a way to postpone triggering syntax highlight until typing is finished?

**Comment by wmjordan** [comment] 2021-06-01 00:33
Thank you for reporting.

![image](https://user-images.githubusercontent.com/12182730/120251376-f0cf8b00-c2b3-11eb-9c18-7909492912bb.png)

I will check to see what's blocking the user interface.

**Comment by wmjordan** [comment] 2021-06-01 03:17
I debugged and found that the syntax highlight was performed on the main thread!
So strange!

Please try the new beta.

**Comment by fitdev** [comment] 2021-06-01 06:22
Thank you for looking into this and providing a new beta so quickly.

Strangely, I never got that VS warning popup about Codist slowing things down.

Unfortunately the new beta has even more issues. Basically performance stayed the same (very slow typing when Syntax Highlight is on). But _now also_ the syntax highlights are almost always wrong:

![2021-06-01 09_14_19-Window](https://user-images.githubusercontent.com/8166847/120275568-33946180-c2ba-11eb-9175-9050c6be917e.jpg)

Here you can see multiple issues with inconsistent colors and font styles being applied to different parts of the same symbol: `Equals`, `GetHashcode`, `int`, `operator`. And what's more it changes with every keystroke, indicating that it is reapplying the style very often, which is what in all likelihood causing the performance issue.

I understand this may be a major task, but perhaps you can rethink how this feature is implemented in an effort to minimize the frequency of style recalculations, and limit them to a narrow scope (like only a few lines that have changed in the last couple of seconds). Then, once the user stopped typing, you can "recalculate" the whole document, which may be needed since new braces / types / etc might have been introduced that could significantly change how the document should be highlighted.

**Comment by fitdev** [comment] 2021-06-01 06:26
[Config.json.zip](https://github.com/wmjordan/Codist/files/6573829/Config.json.zip)

Here's my Config.json in case you need it.

**Comment by wmjordan** [comment] 2021-06-01 07:09
I met with the slow-down when I opened the project Roslyn in VS 2019.10.

If you disabled Codist completely, would you be able to type faster in your huge solution?

I tested the beta with the project Roslyn.
It was a bit faster and I did not encounter the weird highlight results.

**Comment by fitdev** [comment] 2021-06-01 12:01
> If you disabled Codist completely, would you be able to type faster in your huge solution?

Absolutely! Much, much faster - basically then there is no slowdown and everything is smooth.

But I _do not need to disable entire Codist_ - only the Syntax Highlight module. If I disable _just the syntax highlight module_ and then reopen the document, I can type fast. No need to disable the whole Codist.

**Comment by wmjordan** [comment] 2021-06-01 12:50
OMG, as I dug into this issue.... I found it a big task...

**Comment by fitdev** [comment] 2021-06-01 14:18
Hopefully it will worth it in the end!
Otherwise this feature (and I Love it) is not usable on medium/large solutions.

**Comment by wmjordan** [comment] 2021-06-04 10:30
There's a new beta but it does not seem to fully solve this issue.
Please give it a try anyway.

**Comment by fitdev** [comment] 2021-06-04 13:21
Thank you for the new beta. Still seems very laggy compared to when it is turned off. But the inconsistent rendering issue is now gone and everything is highlighted properly and consistently.

**Comment by wmjordan** [comment] 2021-06-05 01:12
I might have to read the source code of Roslyn and develop a similar approach like them to make the syntax highlight running in another thread.

**Comment by fitdev** [comment] 2021-06-05 09:32
I see. Well, I hope you will succeed with this! You have the best syntax highlighter, and it will be really bad if the feature is unusable because of performance issues.

Also just wanted to mention that some features of syntax highlighting like user vs. non-user code are _especially useful_ in large solutions (where there are more serious performance impacts): simply because in a large codebase you may not always remember which ones are framework methods/types and which ones are yours.

**Comment by wmjordan** [comment] 2021-06-15 07:04
Hey, please download the new beta and give it a try. I am trying to make the highlight in asynchronous threads. It's performance should be much better now. Yet it is supposed to be buggy.

However, I at least did not notice the terrible delay when typing into a huge solution (e.g. the _Roslyn_ projects).

**Comment by fitdev** [comment] 2021-06-15 19:03
Thank you for working on this! I will give it a try and let you know soon. From the quick test I have done already - it does seem to be a lot faster now. I will see how it goes.

**Comment by wmjordan** [comment] 2021-06-16 02:14
Thank you for your feedback.
Still quite a few bugs are yet to be fixed.
Please download a new beta which has fixed some of them.

**Comment by fitdev** [comment] 2021-06-17 08:34
Performance seems to be a lot better. It is now usable again! Thanks for your great work!

I have not encountered any major bugs, except perhaps brace color matching no longer works once again.

**Comment by wmjordan** [comment] 2021-06-18 00:26
Oh, I am sorry for the crash.

I planned to rewrite the underlying stuff for NaviBar, SmartBar, etc. after that the updated highlight module becomes stable.
Afterward, Codist should be running even faster and save some energy.

**Comment by wmjordan** [comment] 2021-06-23 01:14
How is your working experience with the beta version?
If no problem, I am planning to release this version and get on with optimizations on NaviBar, SmartBar, etc. afterwards.

**Comment by fitdev** [comment] 2021-06-23 06:21
It seems to be pretty good! But I have not done very extensive testing yet.
BTW, any plans to release 64-bit version for VS 2022 (the first preview is already out)?

**Comment by wmjordan** [comment] 2021-06-23 07:22
No preview version support yet.
I am toooooo busy to have 3 VSes on my computer.
If it is released, I will work on it.

**Comment by fitdev** [comment] 2021-06-23 14:17
Actually just noticed that the performance is still very bad on _large documents_ (say over 500 lines of code). This is not surprising considering it looks that it tries to recolor the whole document. I know this is a difficult issue because a single `{` can change the meaning of most symbols in a document. But perhaps you can try to optimize it somehow. Maybe by querying Roslyn whether there are any errors of certain kind in a document, and if those are present just highlight only the very neighboring lines, not the whole document.

**Comment by wmjordan** [comment] 2021-06-24 00:48
That's weird.
500 lines of code is not so large.
Even in previous versions, it was possible to edit a C# code file with 5000 lines.

I tested several files in the Roslyn projects which had more than 1000 lines of code. There were less than 0.5 second delays while the whole solution was loading on every code editing operations, such as typing, deleting, undoing, etc. But none of them could be _very bad_.

**Comment by fitdev** [comment] 2021-06-24 06:42
> Even in previous versions, it was possible to edit a C# code file with 5000 lines.

Actually I was doing just that yesterday, and towards the end of the file it was really bad: 1 keystroke every second literally! So typing a few words would take ~20 seconds.

Not sure what you mean by
> There were less than 0.5 second delays while the whole solution was loading on every code editing operations, such as typing, deleting, undoing, etc

But even 0.3 second delay is really bad when you are typing. I mean just to see the next character - it should be at most 50ms, otherwise it will really be laggy. Ideally it should not reanalyze the whole document on every keystroke - that's way too expensive.

**Comment by fitdev** [comment] 2021-06-24 06:49
Also, I suspect that at least some performance issue may be related to VS 2019 being 32 bit and GC running too often, or in general it translating its 32 bit calls to underlying 64 bit (my computer and OS are 64 bit). So, with VS 2022 being 64 bit only, the memory pressure will be a lot less, GC will run less often, etc. - performance should improve. Which is why it may be a good idea to test Codist with the new version _sooner_, so that you avoid working on performance issues that _could be solved by moving to 64 bit VS_.

**Comment by fitdev** [comment] 2021-06-24 07:05
Oh, and another thing I noticed. Even if I open a large `cs` file, which is _not_ part of the project (i.e. misc file), it is _still_ highlighted accurately for the most part, and the editing experience is _very fast_ - so the delays have a lot to do with the size of the project for some reason - likely because Roslyn is doing a lot of files processing to resolve all types and extension methods and that takes time.

**Comment by wmjordan** [comment] 2021-06-24 07:06
While I debugged Codist, I was surprised to find that `async` functions in event handlers were running on the Main Thread, which obviously would cause the slow-down--as you have experienced!

![image](https://user-images.githubusercontent.com/12182730/123217594-5272c600-d4fd-11eb-8774-a01eff95e4e4.png)

That was also the reason that I was planning to rewrite the other components.

**Comment by fitdev** [comment] 2021-06-24 07:25
Thank you for pointing this out. But I have _Scrollbar Markers_ module _disabled_. I only have _Super Quick Info_, _Syntax Highlight_, and _NaviBar_ modules enabled.

**Comment by wmjordan** [comment] 2021-06-24 08:10
The NaviBar could also potentially slow down VS--I guess.
Please try a new beta version.

**Comment by fitdev** [comment] 2021-06-28 07:29
The new beta seems to be ok. Though if possible, in the future, you might consider changing the implementation a bit so that it is smarter about the scope of file that needs styles to be recalculated and updated. Too often I see VS revert to its default highlighting momentarily, as I type, and then Codist replaces that original highlighting with its highlighting - and it happens for the whole document, instead of affecting only the nearby lines where I type. But at least it is more performant now.

**Comment by wmjordan** [comment] 2021-06-30 01:40
Please try the new beta.
This one should better prevent VS from reverting to its default highlight and perform a little bit better.

**Comment by fitdev** [comment] 2021-06-30 06:47
Thank you for the new beta. Does it address the memory leak too, or just the highlighting part?

**Comment by wmjordan** [comment] 2021-06-30 09:44
Just the highlight part.

**Comment by wmjordan** [comment] 2021-07-03 00:58
The latest beta had addressed both the memory leak and the highlighting part.
Also, it fixed a problem in the C# Immediate window (caused by previous beta builds) too.

**Comment by fitdev** [comment] 2021-07-03 10:15
Thanks so much for your work! I will try it ASAP. However turns out at the moment I am having issues with VS itself - at least VS 2019 16.11 Preview 2 (latest) - even with Codist completely disabled, I very quickly get to the point of it running out of memory and it effectively freezing. In other words, I cannot properly test Codist's performance since VS itself may be the culprit.

I will switch to VS 2022 Preview for the moment since there memory issues are not as apparent. I did manage to get Codist to work with it too (only Syntax Highlight and NaviBar though) Super QuickInfo does not work. So, perhaps if you can start supporting VS 2022, it will be great.

**Comment by wmjordan** [comment] 2021-07-08 09:20
Have you experience memory leak with the latest Codist?
I suspected that it was not fully fixed. How is the situation on your side?

**Comment by fitdev** [comment] 2021-07-08 13:21
It's still hard to say. I am keeping an eye on this. But as I told you a couple of days before the problem with VS 2019 for me is that it seems to run out of memory even with Codist _fully disabled_. So in my case at least it was not (only) a Codist-related issue. Right now I have Codist enabled in VS 2019 and will see how it goes.

If you are curious, here is the screenshot of the heap map that I took when VS was running out memory with Codist:

![2021-07-01 23_20_06-Snapshot #1 Heap devenv exe (15 28s) (Running) - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/8166847/124928412-3e07f080-e008-11eb-82b0-b36659cf0f24.jpg)

And without Codist:

![2021-07-02 17_28_08-Snapshot #1 Heap devenv exe (3 18s) (Debugging) - Microsoft Visual Studio Previe](https://user-images.githubusercontent.com/8166847/124928689-81faf580-e008-11eb-8675-4b08add0f000.jpg)

Not much difference.

**Comment by fitdev** [comment] 2021-07-08 13:22
But as far as the performance of the highlighting is concerned - it seems to be a lot better now than what it was! So, good work there!

**Comment by fitdev** [comment] 2021-07-08 14:38
Actually you are probably right about memory still leaking. After VS 2019 was close to run out of memory, I took another heap snapshot:

![2021-07-08 17_34_33-DotNet](https://user-images.githubusercontent.com/8166847/124940951-14a09200-e013-11eb-8e54-92fd3e1714b4.jpg)

I suspect that `EventHandler` type and perhaps some other types have something to do with Codist, which was enabled for the session - the NaviBar, Syntax Highligher, and Super QuickInfo.

**Comment by wmjordan** [comment] 2021-07-09 00:21
Thank you very much for helping address this issue.
The leak has something to do with the recent updates.

![image](https://user-images.githubusercontent.com/12182730/125005502-75b97b80-e08e-11eb-996e-4a79bf200054.png)

I will check why so many `ParserTask`s are keep there.

**Comment by fitdev** [comment] 2021-07-09 08:03
Although this is from VS 2022 (I had to switch to it, because VS 2019 is hardly usable at this point for any period of time), there is a similar kind of thing:

![2021-07-09 10_59_53-Snapshot #1 Heap devenv exe (65 63s) (Running) - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/8166847/125044830-069b5180-e0a5-11eb-85c3-d79aca2b7d61.jpg)

In particular:

`EventHandler` - not 100% sure it is Codist-related though.
`Codist.Taggers...`
And perhaps a few other items - you would know better of course which might be related to Codist.

**Comment by wmjordan** [comment] 2021-07-09 08:55
Please download the new beta which has addressed the leak.

**Comment by fitdev** [comment] 2021-07-09 12:04
Thank you for the beta. I have installed it and will let you know how it goes in a few days.

**Comment by wmjordan** [comment] 2021-07-10 13:26
The leak has not been full fixed. Working on it...

**Comment by wmjordan** [comment] 2021-07-12 10:24
Please download and try the new beta.

**Comment by fitdev** [comment] 2021-07-13 05:44
Thank you. Downloaded it. Will let you know if everything is ok in a few days.

**Comment by wmjordan** [comment] 2021-07-13 06:28
This beta should be a little better.
However, I worked a whole morning with the new version and found that there was still some leak if we kept editing a document without closing it.

I will upload a new beta later.

**Comment by fitdev** [comment] 2021-07-13 09:59
Thank you for your efforts! Hope you can start supporting VS 2022 soon, as I am forced to use this version due to VS 2019's memory issues (unrelated to Codist).

**Comment by wmjordan** [comment] 2021-07-16 13:47
There's a new beta. Please give it a try.

**Comment by fitdev** [comment] 2021-07-16 14:58
Thank you! Sorry I did not provide much feedback. But I have not been doing extensive coding in the last few days, and was using VS 2022 more often. Now that VS 2022 Preview 2 is out, hopefully you can make an official version for it too.

I will give the new beta a try and let you know in a couple of days.

**Comment by fitdev** [comment] 2021-07-21 15:33
Sorry for long delay. But at this point I cannot give Codist an accurate assessment, because right now for me VS 2019 is not usable (runs out of memory and becomes unresponsive very quickly), and VS 2022 you do not officially support (but it has its own performance issues).

I think, however, you have already done a good job, so perhaps this issue can be closed. And when I sort out things with VS, if there will still be Codist-related slowdowns, I will open a new issue.

I hope you can release official version for VS 2022 soon (that's what I am using now because of VS 2019's memory issues). They already released Preview 2, and encourage people who use latest DotNet SDKs (like I do) to switch. I think supporting it should be straight forward, as I already managed to get Codist half-working there.

**Comment by wmjordan** [comment] 2021-07-22 00:26
Thank you for your reply. I occasionally check the memory usage of VS 2019 with WinDbg and no longer found serious leak, after days' working with the last beta. I will release this version soon.

The crash of the NaviBar may because VS 2022 has removed a certain DLL files that exist in prior versions. According to the extension migration guide, a separate project is required to build Codist for VS 2022. My schedule is tight at this moment and I am sorry that I can not afford the time on the unstable VS 2022 or promise anything.

**Closed by wmjordan** 2021-07-22 00:26 UTC
Labels: Highlight, enhancement
